services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=clinic_app
      - DB_USERNAME=clinic
      - DB_PASSWORD=secret
    networks:
      - laravel-net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: clinic_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: clinic_app
      POSTGRES_USER: clinic
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clinic -d clinic_app"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  laravel-net:
    driver: bridge